# Pre-commit configuration for TMD Processor
# See https://pre-commit.com for more information

repos:
# Standard pre-commit hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-toml
    -   id: check-json
    -   id: check-added-large-files
        args: ['--maxkb=1024']
    -   id: debug-statements
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: fix-encoding-pragma
        args: ['--remove']

# Import sorting with isort
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)

# Jupyter notebook cleaning
-   repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
    -   id: nbstripout
        files: ".ipynb$"

# Documentation strings check
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        exclude: ^(tests/|examples/|setup.py)
        additional_dependencies: ['tomli']

# ruff - a simple and fast linter for the Rust programming language
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.2
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
