"""
OBJ exporter implementation for TMD.

This module provides the OBJExporter class and related functions for exporting
height maps to OBJ format, which is widely supported across 3D modeling software.
"""

import os
from pathlib import Path
import math
import numpy as np
import logging
from typing import Optional

from ..base import ModelExporter, ExportConfig, MeshData
from ..registry import register_exporter

# Set up logging
logger = logging.getLogger(__name__)


def apply_uv_margin_to_obj_lines(lines: list[str], margin: float) -> list[str]:
    """Remap OBJ vt coordinates into [margin, 1-margin] bbox."""
    if margin <= 0.0 or margin >= 0.5:
        return list(lines)
    us: list[float] = []
    vs: list[float] = []
    for line in lines:
        if not line.startswith("vt "):
            continue
        parts = line.split()
        if len(parts) < 3:
            continue
        try:
            us.append(float(parts[1]))
            vs.append(float(parts[2]))
        except ValueError:
            continue
    if not us:
        return list(lines)
    u_min, u_max = min(us), max(us)
    v_min, v_max = min(vs), max(vs)
    if math.isclose(u_min, u_max) or math.isclose(v_min, v_max):
        return list(lines)
    span = 1.0 - 2.0 * margin
    out: list[str] = []
    for line in lines:
        if line.startswith("vt "):
            parts = line.split()
            if len(parts) >= 3:
                try:
                    u, v = float(parts[1]), float(parts[2])
                    ru = margin + (u - u_min) / (u_max - u_min) * span
                    rv = margin + (v - v_min) / (v_max - v_min) * span
                    suffix = (" " + " ".join(parts[3:])) if len(parts) > 3 else ""
                    out.append(f"vt {ru:.6f} {rv:.6f}{suffix}")
                    continue
                except ValueError:
                    pass
        out.append(line)
    return out


@register_exporter
class OBJExporter(ModelExporter):
    """Exporter for OBJ format."""
    
    # Class attributes
    format_name = "obj"
    file_extensions = ["obj"]
    binary_supported = False
    
    @classmethod
    def export(cls, height_map: np.ndarray, filename: str, config: ExportConfig) -> Optional[str]:
        """Export height map as OBJ file."""
        try:
            # Create mesh
            mesh = cls.create_mesh_from_heightmap(height_map, config)
            
            # Always generate UVs for OBJ
            config.generate_uvs = True
            
            # Prepare mesh using common utilities
            from ..utils.mesh_common import prepare_mesh_for_export
            processed_mesh = prepare_mesh_for_export(mesh, config.__dict__)
            if processed_mesh is None:
                return None
                
            map_bindings = {}
            if getattr(config, "bind_material_maps", False):
                map_bindings = dict(getattr(config, "material_map_bindings", {}) or {})
            if not map_bindings:
                map_bindings = dict(getattr(config, "extra", {}).get("material_map_bindings", {}) or {})

            # Export processed mesh
            write_obj(
                processed_mesh,
                filename,
                include_materials=True,
                material_map_bindings=map_bindings,
            )
            
            return filename
            
        except Exception as e:
            logger.error(f"OBJ export failed: {e}")
            return None


def write_obj(
    mesh: MeshData, 
    filename: str,
    include_materials: bool = True,
    material_map_bindings: Optional[dict[str, str]] = None,
    material_name: str = "TerrainMaterial",
) -> None:
    """
    Write mesh data to an OBJ file.
    
    Args:
        mesh: MeshData object containing the mesh to export
        filename: Output filename
        include_materials: Whether to include material definitions
    """
    with open(filename, 'w') as f:
        # Write header
        f.write("# OBJ file generated by TMD exporter\n")
        
        # Reference material file if needed
        if include_materials:
            mtl_filename = os.path.splitext(os.path.basename(filename))[0] + ".mtl"
            f.write(f"mtllib {mtl_filename}\n")
            
            # Create MTL file
            create_mtl_file(
                os.path.join(os.path.dirname(filename), mtl_filename),
                material_map_bindings=material_map_bindings,
                obj_dir=os.path.dirname(filename),
                material_name=material_name,
            )
            
        # Write object name
        f.write("o HeightMap\n")
        
        # Write vertex data
        for v in mesh.vertices:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        
        # Write texture coordinates
        if mesh.uvs is not None:
            for uv in mesh.uvs:
                f.write(f"vt {uv[0]:.6f} {uv[1]:.6f}\n")
        
        # Write normals
        if mesh.normals is not None:
            for n in mesh.normals:
                f.write(f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}\n")
        
        # Apply material if available
        if include_materials:
            f.write(f"usemtl {material_name}\n")
        
        # Write faces (OBJ uses 1-based indexing)
        # Format is: f v1/vt1/vn1 v2/vt2/vn2 v3/vt3/vn3
        for face in mesh.faces:
            indices = [i+1 for i in face]  # OBJ indices start at 1
            
            if mesh.uvs is not None and mesh.normals is not None:
                # Full format with vertices, UVs, and normals
                f.write(f"f {indices[0]}/{indices[0]}/{indices[0]} "
                        f"{indices[1]}/{indices[1]}/{indices[1]} "
                        f"{indices[2]}/{indices[2]}/{indices[2]}\n")
            elif mesh.uvs is not None:
                # Vertices and UVs
                f.write(f"f {indices[0]}/{indices[0]} "
                        f"{indices[1]}/{indices[1]} "
                        f"{indices[2]}/{indices[2]}\n")
            else:
                # Vertices only
                f.write(f"f {indices[0]} {indices[1]} {indices[2]}\n")


def create_mtl_file(
    mtl_filename: str,
    material_map_bindings: Optional[dict[str, str]] = None,
    obj_dir: Optional[str] = None,
    material_name: str = "TerrainMaterial",
) -> None:
    """
    Create a simple MTL material file for the OBJ.
    
    Args:
        mtl_filename: Path to the MTL file
    """
    material_map_bindings = material_map_bindings or {}
    base = Path(obj_dir) if obj_dir else Path(mtl_filename).parent

    def _rel(path: str) -> str:
        p = Path(path)
        try:
            return p.resolve().relative_to(base.resolve()).as_posix()
        except Exception:
            return os.path.relpath(str(p), str(base)).replace("\\", "/")

    with open(mtl_filename, 'w', encoding='utf-8') as f:
        f.write("# MTL file generated by TMD exporter\n")
        f.write(f"newmtl {material_name}\n")
        f.write("Ka 0.2 0.2 0.2\n")  # Ambient color
        f.write("Kd 0.8 0.8 0.8\n")  # Diffuse color
        f.write("Ks 0.1 0.1 0.1\n")  # Specular color
        f.write("Ns 100.0\n")        # Specular exponent (shininess)
        f.write("illum 2\n")         # Illumination model (2 = highlight on)
        if material_map_bindings.get("map_kd"):
            f.write(f"map_Kd {_rel(material_map_bindings['map_kd'])}\n")
        if material_map_bindings.get("map_bump"):
            f.write(f"map_Bump {_rel(material_map_bindings['map_bump'])}\n")
        if material_map_bindings.get("map_disp"):
            f.write(f"map_disp {_rel(material_map_bindings['map_disp'])}\n")
        if material_map_bindings.get("map_pr"):
            f.write(f"map_Pr {_rel(material_map_bindings['map_pr'])}\n")