"""Surface metrics: areal curvature and tribology-oriented height-map quantities."""

from __future__ import annotations

from . import tribology as surfalize
from .curvature import (
    OrientationHistograms,
    mean_curvature,
    mean_curvature_from_derivatives,
    normal_density_on_sphere,
    normal_orientation_summary,
    orientation_histograms,
    per_pixel_normal_change_deg,
    pixel_spacing_dy_dx_from_metadata,
    surface_normals_flat,
    surface_normals_grid,
)
from .texture import surface_metrics_summary, texture_direction_spectrum
from .tribology import (
    NormalizeMode,
    _asymmetry_from_three_angles,
    _circular_mean_angle_weighted,
    _preprocess_plane,
    bearing_analysis,
    bearing_area_curve,
    cell_sizes_from_metadata,
    debris_pocket_map,
    debris_pocket_score,
    depth_at_rmr,
    interfacial_shear_proxy_map,
    local_rms,
    material_ratio_curve,
    preferred_slip_axis,
    remove_least_squares_plane,
    slide_azimuth_rad_from_direction,
    texture_modulated_pair_friction_maps,
    rmr_at_depths,
    save_tribology_dashboard_png,
    shear_proxy_map,
    shear_proxy_uint8,
    summit_curvature_map,
)
from .tribology_maps import debris_pocket_map_01, shear_hazard_map_01

__all__ = [
    "NormalizeMode",
    "OrientationHistograms",
    "surfalize",
    "_asymmetry_from_three_angles",
    "_circular_mean_angle_weighted",
    "_preprocess_plane",
    "bearing_analysis",
    "bearing_area_curve",
    "cell_sizes_from_metadata",
    "debris_pocket_map_01",
    "debris_pocket_map",
    "debris_pocket_score",
    "depth_at_rmr",
    "interfacial_shear_proxy_map",
    "local_rms",
    "material_ratio_curve",
    "mean_curvature",
    "mean_curvature_from_derivatives",
    "normal_density_on_sphere",
    "normal_orientation_summary",
    "orientation_histograms",
    "per_pixel_normal_change_deg",
    "pixel_spacing_dy_dx_from_metadata",
    "preferred_slip_axis",
    "remove_least_squares_plane",
    "slide_azimuth_rad_from_direction",
    "texture_modulated_pair_friction_maps",
    "rmr_at_depths",
    "shear_hazard_map_01",
    "shear_proxy_map",
    "shear_proxy_uint8",
    "summit_curvature_map",
    "surface_metrics_summary",
    "surface_normals_flat",
    "surface_normals_grid",
    "save_tribology_dashboard_png",
    "texture_direction_spectrum",
]
